// Code generated by protoc-gen-go.
// source: baseProto.proto
// DO NOT EDIT!

/*
Package gameProto is a generated protocol buffer package.

It is generated from these files:
	baseProto.proto

It has these top-level messages:
	BaseMessage
	GameUserInfo
*/
package gameProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_UNKNOWN       MessageType = 0
	MessageType_GAME_USERINFO MessageType = 1
)

var MessageType_name = map[int32]string{
	0: "UNKNOWN",
	1: "GAME_USERINFO",
}
var MessageType_value = map[string]int32{
	"UNKNOWN":       0,
	"GAME_USERINFO": 1,
}

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}
func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (x *MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageType_value, data, "MessageType")
	if err != nil {
		return err
	}
	*x = MessageType(value)
	return nil
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// required 必填
// optional 可选
type BaseMessage struct {
	Mid              *int32 `protobuf:"varint,1,req,name=mid" json:"mid,omitempty"`
	Serialization    []byte `protobuf:"bytes,2,req,name=serialization" json:"serialization,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BaseMessage) Reset()                    { *m = BaseMessage{} }
func (m *BaseMessage) String() string            { return proto.CompactTextString(m) }
func (*BaseMessage) ProtoMessage()               {}
func (*BaseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseMessage) GetMid() int32 {
	if m != nil && m.Mid != nil {
		return *m.Mid
	}
	return 0
}

func (m *BaseMessage) GetSerialization() []byte {
	if m != nil {
		return m.Serialization
	}
	return nil
}

type GameUserInfo struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Uname            *string `protobuf:"bytes,2,opt,name=uname" json:"uname,omitempty"`
	Facebookid       *string `protobuf:"bytes,3,opt,name=facebookid" json:"facebookid,omitempty"`
	SetFlagCount     *int32  `protobuf:"varint,4,opt,name=setFlagCount" json:"setFlagCount,omitempty"`
	FoundFlagCount   *int32  `protobuf:"varint,5,opt,name=foundFlagCount" json:"foundFlagCount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GameUserInfo) Reset()                    { *m = GameUserInfo{} }
func (m *GameUserInfo) String() string            { return proto.CompactTextString(m) }
func (*GameUserInfo) ProtoMessage()               {}
func (*GameUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GameUserInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *GameUserInfo) GetUname() string {
	if m != nil && m.Uname != nil {
		return *m.Uname
	}
	return ""
}

func (m *GameUserInfo) GetFacebookid() string {
	if m != nil && m.Facebookid != nil {
		return *m.Facebookid
	}
	return ""
}

func (m *GameUserInfo) GetSetFlagCount() int32 {
	if m != nil && m.SetFlagCount != nil {
		return *m.SetFlagCount
	}
	return 0
}

func (m *GameUserInfo) GetFoundFlagCount() int32 {
	if m != nil && m.FoundFlagCount != nil {
		return *m.FoundFlagCount
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseMessage)(nil), "gameProto.BaseMessage")
	proto.RegisterType((*GameUserInfo)(nil), "gameProto.GameUserInfo")
	proto.RegisterEnum("gameProto.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("baseProto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x6a, 0x90, 0x4c, 0x52, 0x8d, 0x83, 0x87, 0x3d, 0x49, 0x08, 0x22, 0x41, 0xd0,
	0x77, 0x50, 0x49, 0x4b, 0x91, 0xa6, 0xb2, 0x1a, 0x3c, 0xca, 0xd4, 0x4c, 0xc2, 0x62, 0xb3, 0x5b,
	0xb2, 0xc9, 0x41, 0x1f, 0xc7, 0x27, 0x95, 0xb4, 0x05, 0x6d, 0x2f, 0xc3, 0x3f, 0xdf, 0xfc, 0x7c,
	0x30, 0x70, 0xb6, 0x24, 0xcb, 0xcf, 0xad, 0xe9, 0xcc, 0xdd, 0x7a, 0x98, 0xe8, 0xd7, 0xd4, 0x6c,
	0x41, 0x92, 0x41, 0xf0, 0x40, 0x96, 0xe7, 0x6c, 0x2d, 0xd5, 0x8c, 0x11, 0x8c, 0x1a, 0x55, 0x0a,
	0x27, 0x76, 0x53, 0x4f, 0x0e, 0x11, 0xaf, 0x60, 0x6c, 0xb9, 0x55, 0xb4, 0x52, 0xdf, 0xd4, 0x29,
	0xa3, 0x85, 0x1b, 0xbb, 0x69, 0x28, 0xf7, 0x61, 0xf2, 0xe3, 0x40, 0x38, 0xa5, 0x86, 0x0b, 0xcb,
	0xed, 0x4c, 0x57, 0x66, 0x10, 0xf5, 0x3b, 0x91, 0x2f, 0x87, 0x88, 0x17, 0xe0, 0xf5, 0x9a, 0x1a,
	0x16, 0x6e, 0xec, 0xa4, 0xbe, 0xdc, 0x2e, 0x78, 0x09, 0x50, 0xd1, 0x07, 0x2f, 0x8d, 0xf9, 0x54,
	0xa5, 0x18, 0x6d, 0x4e, 0xff, 0x08, 0x26, 0x10, 0x5a, 0xee, 0x26, 0x2b, 0xaa, 0x1f, 0x4d, 0xaf,
	0x3b, 0x71, 0x1c, 0x3b, 0xa9, 0x27, 0xf7, 0x18, 0x5e, 0xc3, 0x69, 0x65, 0x7a, 0x5d, 0xfe, 0xb5,
	0xbc, 0x4d, 0xeb, 0x80, 0xde, 0xdc, 0x42, 0xb0, 0xfb, 0xf3, 0xf5, 0x6b, 0xcd, 0x18, 0xc0, 0x49,
	0x91, 0x3f, 0xe5, 0x8b, 0xb7, 0x3c, 0x3a, 0xc2, 0x73, 0x18, 0x4f, 0xef, 0xe7, 0xd9, 0x7b, 0xf1,
	0x92, 0xc9, 0x59, 0x3e, 0x59, 0x44, 0xce, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x5a, 0xdd,
	0x49, 0x37, 0x01, 0x00, 0x00,
}
